### ISSUE TITLE
android port?

### ISSUE THREAD

**Issue by Madeline0110** [mcpower/icallate#4]
Hi, really cool project. Was wondering if you are considering making a port for android? Or if you are aware of one that already exists.

**Comment by mcpower** [comment]
No - I'm employed now and not in university, so I don't have the free time to develop such a thing (and I'd also need to get approval from my employer which is a huge pain). I believe some similar apps may already exist, and if not you can make one yourself if you have the know-how :D

You can try using iCallate on a mobile browser, though - do the steps normally and follow the "not using those browsers" step. Instead of pasting it into the developer console, paste it in the address bar with `javascript:` in front so it looks like `javascript:$(document`..., then press enter. Let me know if that works!

**Comment by Madeline0110** [comment]
I'm so sorry, total misunderstanding on my part (saw the i in iCallate and assumed it was an IOS implementation only, should have properly read the readme). If you don't mind me asking, why does your employer have a say over what side projects you undertake in your spare time? I will probably be working in the same industry and I'm interested in learning anything I can about it.

Also the software works great, and all my friends got great use out of it.

**Comment by mcpower** [comment]
No problem - iCallate is named after [the iCalendar file format](https://en.wikipedia.org/wiki/ICalendar) which could definitely be confusing.

> why does your employer have a say over what side projects you undertake in your spare time?

I believe it's mostly to prevent conflicts of interest (and also to prevent employees being occupied with other projects). Some employment contracts have a clause which state that all intellectual property you make during your employment is their property, unless they grant an explicit exemption.

**Comment by Madeline0110** [comment]
Ah I see, thanks for the explanation
